### PR TITLE
Add standalone url field to fx2 setup.py

### PR DESCRIPTION
**Pull request by artizirk**
This should add a visible homepage link to pypi sidebar [1] on next
release upload.

[1]:https://pypi.org/project/fx2/

### CODE REVIEW

**Comment by whitequark** [comment]
Huh. Why don't these links already show up in sidebar?

**Comment by artizirk** [comment]
It could be some edge case with url metadata handling, [twine](https://github.com/pypa/twine/blob/master/setup.cfg#L8-L13) also uses `project_urls` field and those show up fine. I will try to dig deeper to figure out whats going on.

**Comment by artizirk** [comment]
So, I did some testing with [testpypi](https://packaging.python.org/guides/using-testpypi/) and it looks like both, with and without the `url` field show all three `project_urls` links.

Also `python3 setup.py check` does complain about missing `url` meta-data

```
$ python3 setup.py check
running check
warning: Check: missing required meta-data: url
```

Package upload to testpypi was done with twine 2.0.0. I don't know it that has something to do with missing links.

Screenshot_2020-06-03 fx2

Screenshot_2020-06-03 fx2(1)

**Comment by whitequark** [comment]
Okay so the only thing I have to do here is to upload the package again with twine, right?

**Comment by artizirk** [comment]
I think so yes.

**Comment by whitequark** [comment]
I've uploaded with twine but there are still no project links anywhere.

**Comment by whitequark** [comment]
The links are fixed now: https://pypi.org/project/fx2/

**Pull request closed without merging**
