### PR TITLE
Make it look for 'sdcc-sdcc' and 'sdcc-sdas8051' executables too

### PR DESCRIPTION
**Pull request by purdeaandrei**
This is the name of the executables on fedora (tested on fedora:latest docker container)

### CODE REVIEW

**Comment by whitequark** [comment]
I'm not really happy with the complexity this adds; I also don't particularly like the idea of maintaining a set of workarounds for individual distros. Why does Fedora do this anyway?

**Comment by whitequark** [comment]
I think a better approach would be to make sure we have the definitions of

```
SDCC = sdcc
SDAR = sdar
SDAS8051 = sdas8051
```

and then separate ones that include the common flags, something like `RUN_SDCC = $(SDCC) ...`.

**Comment by purdeaandrei** [comment]
> I'm not really happy with the complexity this adds; I also don't particularly like the idea of maintaining a set of workarounds for individual distros. Why does Fedora do this anyway?

Looks like it's been like this since 2007.
Changelog:
image
And I also found a fedora readme:
image

Which I checked, indeed the real executables are in libexec, and bin only contains shell scripts that pass on to libexec.

Perhaps we can add a note to the glasgow firmware, to add `/usr/libexec/sdcc` to PATH, does that sound acceptable?

**Comment by whitequark** [comment]
> Perhaps we can add a note to the glasgow firmware, to add `/usr/libexec/sdcc` to PATH, does that sound acceptable?

Yeah.

**Comment by purdeaandrei** [comment]
Alright, I'll close this PR.

**Pull request closed without merging**
